version: '3'
services:
  node:
    image: node:8.10
    command: bash -c "yarn install && yarn start"
    volumes:
      - .:/var/repo
    ports:
      - "3000:3000"
    environment:
      REACT_APP_ENV: development
    working_dir: /var/repo
