version: '3'
services:
  node:
    image: node:8.10
    command: bash
    volumes:
      - .:/var/repo
    ports:
      - "3000:3000"
    environment:
      FIREBASE_TOKEN: $FIREBASE_TOKEN
    working_dir: /var/repo
